# Example Site settings

#google_analytics: UA-NNNNNNNN-N

title: 'Cuong Nguyen'

header_pages:
 - index.md
 - about.md
 
footer: 

# Build settings
# markdown: kramdown
# plugins:
#   - jekyll-seo-tag
